language: node_js
node_js:
- node
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgcc-4.9-dev
    - libstdc++-4.9-dev
    - libobjc-4.9-dev
    - libjsoncpp0
    - libobjc-4.9-dev
    - libstdc++6

before_install:
- wget http://famreiser.ch/llvm/llvm-5.0-webassembly.tar.gz
- mkdir llvm && tar -xzf llvm-5.0-webassembly.tar.gz -C llvm
- cd llvm && ls -al . && sudo dpkg -i clang-5.0_5.0~svn298096-1~exp1_amd64.deb libclang1-5.0_5.0~svn298096-1~exp1_amd64.deb libclang-5.0-dev_5.0~svn298096-1~exp1_amd64.deb libclang-common-5.0-dev_5.0~svn298096-1~exp1_amd64.deb libllvm5.0_5.0~svn298096-1~exp1_amd64.deb llvm-5.0_5.0~svn298096-1~exp1_amd64.deb llvm-5.0-runtime_5.0~svn298096-1~exp1_amd64.deb llvm-5.0-dev_5.0~svn298096-1~exp1_amd64.deb && cd ..
- export CC="clang-5.0"
- export CXX="clang++-5.0"
- export LLVM=/usr/local/bin

install:
- llvm-config-5.0 --version || true
- npm install llvm-node --LLVM_CONFIG=llvm-config-5.0
- npm install
- npm run bootstrap || true
- cat npm-debug.log || true
- cat packages/compiler/npm-debug.log || true
- cat packages/runtime/npm-debug.log || true
- cat packages/benchmark/npm-debug.log || true
- cat lerna-debug.log || true
- exit 1
- npm run build

after_failure:
- cat npm-debug.log || true
- cat lerna-debug.log || true
